version: '3.4'

networks:
  frontend:
  backend:

services:
  mssqlserver:
    image: "mcr.microsoft.com/mssql/server:latest"
    environment: 
     ACCEPT_EULA: Y
     SA_PASSWORD: Event@API
    ports:
     - "1448:1433"
    container_name: eventssqlserver
    networks:
     - backend

  eventcatalogapi:
    image: events/eventscatalogapi
    build:
      context: ./EventCatalogAPI
      dockerfile: Dockerfile
    environment:
      Externalbaseurl: http://localhost:7000
      DatabaseServer: mssqlserver
      DatabaseName: EventCatalog
      DatabaseUser: sa
      DatabasePassword: Event@API
    ports:
      - "7000:80"
    container_name: eventscatalogapi
    networks:
      - frontend
      - backend
    depends_on:
      - mssqlserver
  webmvc:
    image: events/webmvc
    build:
      context: .\WebMVC
      dockerfile: Dockerfile
    environment:
      EventCatalogUrl: http://eventcatalogapi
    ports:
      - "7500:80"
    networks:
      - frontend
    container_name: eventcatalogweb
    depends_on:
     - eventcatalogapi
       



       
   
     