version: '3.4'

networks:
  frontend:
  backend:

services:
  mssqlserver:
    image: "mcr.microsoft.com/mssql/server:latest"
    environment: 
     ACCEPT_EULA: Y
     SA_PASSWORD: Event@API
    ports:
     - "1448:1433"
    container_name: eventssqlserver
    networks:
     - backend

  tokensqlserver:
    image: "mcr.microsoft.com/mssql/server:latest"
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: ProductApi(!)
    ports:
      - "1449:1433"
    container_name: eventtokensqlserver
    networks:
      - backend
  
  ordersqlserver:
    image: "mcr.microsoft.com/mssql/server:latest"
    environment: 
     ACCEPT_EULA: Y
     SA_PASSWORD: Event@API
    ports:
     - "1450:1433"
    container_name: eventsordersqlserver
    networks:
     - backend

  basket.data:
    image: redis
    ports:
    - "7050:6379"
    container_name: basketdata
    networks:
     - backend

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: myrabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
      - "5671:5671"
    volumes:
      - ~/rabbitmq:/var/lib/rabbitmq/mnesia   
    networks:
      - backend 

  eventcatalogapi:
    image: events/eventscatalogapi
    build:
      context: .\EventCatalogAPI
      dockerfile: Dockerfile
    environment:
      Externalbaseurl: http://localhost:7000
      DatabaseServer: mssqlserver
      DatabaseName: EventCatalog
      DatabaseUser: sa
      DatabasePassword: Event@API
    ports:
      - "7000:80"
    container_name: eventscatalogapi
    networks:
      - frontend
      - backend
    depends_on:
      - mssqlserver

  order:
    image: events/orderapi
    build:
      context: ./OrderAPI
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      IdentityUrl: http://192.168.86.29:7800
      DatabaseServer: ordersqlserver
      DatabaseName: OrdersDb
      DatabaseUser: sa
      DatabasePassword: Event@API
    ports:
      - "7020:80"
    container_name: eventsorderapi
    networks:
      - frontend
      - backend
    depends_on:
      - tokenserver
      - ordersqlserver
      - rabbitmq

  cartapi:
     image: events/cartapi
     build:
      context: .\EventCatalogAPI
      dockerfile: Dockerfile
     environment:
      IdentityUrl: http://192.168.86.29:7800
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionString: basket.data
     ports:
      - "7010:80"
     container_name: cartapi
     networks:
      - backend
      - frontend
     depends_on:
      - tokenserver
      - basket.data
      - rabbitmq

  webmvc:
    image: events/webmvc
    build:
      context: .\WebMVC
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      EventCatalogUrl: http://eventcatalogapi
      OrderUrl: http://order
      IdentityUrl: http://192.168.86.29:7800
      CallBackUrl: http://localhost:7500
      StripePublicKey: pk_test_51KtHsOIDh35UR516CGbTXBqrF5dHB4oDgSsaTRN4XqyhlrFGHxZ1Dt5gUaX6KbOpOGSIMtMzxZSHvvLRcTcJAyRY00EBaqy2bV
      StripePrivateKey: sk_test_51KtHsOIDh35UR516bV9GPbBwMIOXH3oP2BYhNcwT4aYeLnjwoxdHw93TldnXmJ6KiaBmRkuz8aoFe2YKeW8Yl4vY00wHNP78mx
    ports:
      - "7500:80"
    networks:
      - frontend
    container_name: eventcatalogweb
    depends_on:
     - eventcatalogapi
     - tokenserver
     - cartapi
     - order
  
  tokenserver:
    build:
      context: .\TokenServiceAPI
      dockerfile: Dockerfile
    image: events/tokenapi
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      MvcClient: http://localhost:7500
      BasketApiClient: http://localhost:7510
      OrderApiClient: http://localhost:7520
    ports:
      - "7800:80"
    container_name: tokenserviceapi
    networks:
      - backend
      - frontend
    depends_on:
      - tokensqlserver

       



       
   
     